#include "bsp.h"
#include "system.h"



void BSP_Button_Init(){
    _BTNU_MODE = GPIO_MODE_INPUT;
	_BTNL_MODE = GPIO_MODE_INPUT;
	_BTNR_MODE = GPIO_MODE_INPUT;
	_BTND_MODE = GPIO_MODE_INPUT;
}

void BSP_Switch_Init(){
    _SW0_MODE = GPIO_MODE_INPUT;
	_SW1_MODE = GPIO_MODE_INPUT;
	_SW2_MODE = GPIO_MODE_INPUT;
	_SW3_MODE = GPIO_MODE_INPUT;
	_SW4_MODE = GPIO_MODE_INPUT;
	_SW5_MODE = GPIO_MODE_INPUT;
	_SW6_MODE = GPIO_MODE_INPUT;    
	_SW7_MODE = GPIO_MODE_INPUT;
	_SW8_MODE = GPIO_MODE_INPUT;
	_SW9_MODE = GPIO_MODE_INPUT;
	_SW10_MODE = GPIO_MODE_INPUT;
	_SW11_MODE = GPIO_MODE_INPUT;
	_SW12_MODE = GPIO_MODE_INPUT;
	_SW13_MODE = GPIO_MODE_INPUT;
	_SW14_MODE = GPIO_MODE_INPUT;
	_SW15_MODE = GPIO_MODE_INPUT;
}